Update deploy-to-k8s to support multiple auth methods

diff --git a/.github/workflows/deploy-to-k8s.yml b/.github/workflows/deploy-to-k8s.yml
--- a/.github/workflows/deploy-to-k8s.yml
+++ b/.github/workflows/deploy-to-k8s.yml
@@ -1,13 +1,13 @@
 name: Deploy to Kubernetes
 
-# This workflow uses workload identity federation, and requires that the
-# appropriate policy binding has been set up for the calling repository. See if
-# it has with:
+# When used with auth_method "gke", this workflow uses workload identity
+# federation, and requires that the appropriate policy binding has been set up
+# for the calling repository. See if it has with:
 #
 #     gcloud iam service-accounts get-iam-policy deploy@replicate-production.iam.gserviceaccount.com
 #
-# Note that the calling workflow will also need to specify the
-# appropriate permissions on the job that uses this workflow, e.g.
+# Note that the calling workflow will also need to specify the appropriate
+# permissions on the job that uses this workflow, e.g.
 #
 #     deploy:
 #       permissions:
@@ -18,18 +18,16 @@ name: Deploy to Kubernetes
 on:
   workflow_call:
     inputs:
-      cluster_name:
+      auth_method:
         required: true
         type: string
-        description: The name of the cluster
-      location:
-        required: true
+        description: How to authenticate to the cluster (one of "kubeconfig", "gke").
+      auth_params:
         type: string
-        description: The location (region or zone) of the cluster
-      project_id:
-        required: true
-        type: string
-        description: The parent GCP project ID (NOT project number) of the cluster
+        description: >
+          Auth payload for the specified auth mechanism. For auth_method "gke"
+          this should be a JSON string representing the inputs to
+          google-github-actions/get-gke-credentials.
       run:
         required: true
         type: string
@@ -41,7 +39,7 @@ on:
       install_helm:
         required: false
         type: boolean
-        description: Whether this deployment needs helm to be installed (also installs sops and helm-secrets)
+        description: Whether this deployment needs helm to be installed (installs helm-secrets if install_sops is also specified)
         default: false
       install_kustomize:
         required: false
@@ -56,6 +54,8 @@ on:
     secrets:
       HONEYCOMB_API_KEY:
         required: true
+      KUBECONFIG:
+        required: false
 
 jobs:
   deploy:
@@ -71,18 +71,30 @@ jobs:
     steps:
       - uses: actions/checkout@master
 
+      - name: Validate auth method
+        if: ${{ inputs.auth_method != 'gke' && inputs.auth_method != 'kubeconfig' }}
+        run: |-
+          echo "Invalid auth method: must be one of kubeconfig, gke" >&2
+          exit 1
+
       - name: Authenticate to Google Cloud
+        if: ${{ inputs.auth_method == 'gke' || inputs.install_sops }}
         uses: google-github-actions/auth@v1
         with:
           workload_identity_provider: projects/1025538909507/locations/global/workloadIdentityPools/github/providers/github-actions
           service_account: deploy@replicate-production.iam.gserviceaccount.com
 
-      - name: Fetch cluster credentials
+      - name: Install cluster credentials (GKE)
+        if: ${{ inputs.auth_method == 'gke' }}
         uses: google-github-actions/get-gke-credentials@v1
+        with: ${{ fromJSON(inputs.auth_params) }}
+
+      - name: Install cluster credentials (kubeconfig)
+        if: ${{ inputs.auth_method == 'kubeconfig' }}
+        uses: azure/k8s-set-context@v3
         with:
-          cluster_name: ${{ inputs.cluster_name }}
-          location: ${{ inputs.location }}
-          project_id: ${{ inputs.project_id }}
+          method: kubeconfig
+          kubeconfig: ${{ secrets.KUBECONFIG }}
 
       - name: Install sops
         if: ${{ inputs.install_sops }}
